### ISSUE TITLE
[Bug] Admin 사이트 테스트 해보며 버그 잡기

### ISSUE THREAD

**Issue by leeyounagh** [team-echoist/web-frontend#34]

**Comment by maxisneverthat** [comment]
today essay 페이지 진입시 요청 응답이 204. 응답받은 데이터가없어서 그래프가 자유분방함
![Image](https://github.com/team-echoist/web-frontend/assets/103374153/60f0913e-581b-4535-ad34-650000e7f103)



근데 새로고침하면 정상적으로 통신이 끝남
![Image](https://github.com/team-echoist/web-frontend/assets/103374153/2cad14f8-2069-4db4-a388-7e40c8eaf05e)

**Comment by leeyounagh** [comment]
오노... 확인해보겠습니다 ㅎㅎ

**Comment by leeyounagh** [comment]
완료!
